// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SpaceTraders.Client.Systems.Item.Waypoints.Item.Construction;
using SpaceTraders.Client.Systems.Item.Waypoints.Item.JumpGate;
using SpaceTraders.Client.Systems.Item.Waypoints.Item.Market;
using SpaceTraders.Client.Systems.Item.Waypoints.Item.Shipyard;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SpaceTraders.Client.Systems.Item.Waypoints.Item {
    /// <summary>
    /// Builds and executes requests for operations under \systems\{systemSymbol}\waypoints\{waypointSymbol}
    /// </summary>
    public class WithWaypointSymbolItemRequestBuilder : BaseRequestBuilder {
        /// <summary>The construction property</summary>
        public ConstructionRequestBuilder Construction { get =>
            new ConstructionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jumpGate property</summary>
        public JumpGateRequestBuilder JumpGate { get =>
            new JumpGateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The market property</summary>
        public MarketRequestBuilder Market { get =>
            new MarketRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shipyard property</summary>
        public ShipyardRequestBuilder Shipyard { get =>
            new ShipyardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new WithWaypointSymbolItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWaypointSymbolItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/systems/{systemSymbol}/waypoints/{waypointSymbol}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new WithWaypointSymbolItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWaypointSymbolItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/systems/{systemSymbol}/waypoints/{waypointSymbol}", rawUrl) {
        }
        /// <summary>
        /// View the details of a waypoint.If the waypoint is uncharted, it will return the &apos;Uncharted&apos; trait instead of its actual traits.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<WithWaypointSymbolGetResponse?> GetAsWithWaypointSymbolGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default) {
#nullable restore
#else
        public async Task<WithWaypointSymbolGetResponse> GetAsWithWaypointSymbolGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default) {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<WithWaypointSymbolGetResponse>(requestInfo, WithWaypointSymbolGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// View the details of a waypoint.If the waypoint is uncharted, it will return the &apos;Uncharted&apos; trait instead of its actual traits.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsWithWaypointSymbolGetResponse instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<WithWaypointSymbolResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default) {
#nullable restore
#else
        public async Task<WithWaypointSymbolResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default) {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<WithWaypointSymbolResponse>(requestInfo, WithWaypointSymbolResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// View the details of a waypoint.If the waypoint is uncharted, it will return the &apos;Uncharted&apos; trait instead of its actual traits.
        /// </summary>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default) {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default) {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public WithWaypointSymbolItemRequestBuilder WithUrl(string rawUrl) {
            return new WithWaypointSymbolItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class WithWaypointSymbolItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters> {
        }
    }
}
