// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.My.Ships.Item.Refine {
    /// <summary>The type of good to produce out of the refining process.</summary>
    public enum RefinePostRequestBody_produce {
        [EnumMember(Value = "IRON")]
        IRON,
        [EnumMember(Value = "COPPER")]
        COPPER,
        [EnumMember(Value = "SILVER")]
        SILVER,
        [EnumMember(Value = "GOLD")]
        GOLD,
        [EnumMember(Value = "ALUMINUM")]
        ALUMINUM,
        [EnumMember(Value = "PLATINUM")]
        PLATINUM,
        [EnumMember(Value = "URANITE")]
        URANITE,
        [EnumMember(Value = "MERITIUM")]
        MERITIUM,
        [EnumMember(Value = "FUEL")]
        FUEL,
    }
}
