// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>
    /// The details of the required construction materials for a given waypoint under construction.
    /// </summary>
    public class ConstructionMaterial : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of units fulfilled toward the required amount.</summary>
        public int? Fulfilled { get; set; }
        /// <summary>The number of units required.</summary>
        public int? Required { get; set; }
        /// <summary>The good&apos;s symbol.</summary>
        public SpaceTraders.Client.Models.TradeSymbol? TradeSymbol { get; set; }
        /// <summary>
        /// Instantiates a new ConstructionMaterial and sets the default values.
        /// </summary>
        public ConstructionMaterial() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ConstructionMaterial CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ConstructionMaterial();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"fulfilled", n => { Fulfilled = n.GetIntValue(); } },
                {"required", n => { Required = n.GetIntValue(); } },
                {"tradeSymbol", n => { TradeSymbol = n.GetEnumValue<TradeSymbol>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("fulfilled", Fulfilled);
            writer.WriteIntValue("required", Required);
            writer.WriteEnumValue<TradeSymbol>("tradeSymbol", TradeSymbol);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
