// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>Type of contract.</summary>
    public enum Contract_type {
        [EnumMember(Value = "PROCUREMENT")]
        PROCUREMENT,
        [EnumMember(Value = "TRANSPORT")]
        TRANSPORT,
        [EnumMember(Value = "SHUTTLE")]
        SHUTTLE,
    }
}
