// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The symbol of the faction.</summary>
    public enum FactionSymbol {
        [EnumMember(Value = "COSMIC")]
        COSMIC,
        [EnumMember(Value = "VOID")]
        VOID,
        [EnumMember(Value = "GALACTIC")]
        GALACTIC,
        [EnumMember(Value = "QUANTUM")]
        QUANTUM,
        [EnumMember(Value = "DOMINION")]
        DOMINION,
        [EnumMember(Value = "ASTRO")]
        ASTRO,
        [EnumMember(Value = "CORSAIRS")]
        CORSAIRS,
        [EnumMember(Value = "OBSIDIAN")]
        OBSIDIAN,
        [EnumMember(Value = "AEGIS")]
        AEGIS,
        [EnumMember(Value = "UNITED")]
        UNITED,
        [EnumMember(Value = "SOLITARY")]
        SOLITARY,
        [EnumMember(Value = "COBALT")]
        COBALT,
        [EnumMember(Value = "OMEGA")]
        OMEGA,
        [EnumMember(Value = "ECHO")]
        ECHO,
        [EnumMember(Value = "LORDS")]
        LORDS,
        [EnumMember(Value = "CULT")]
        CULT,
        [EnumMember(Value = "ANCIENTS")]
        ANCIENTS,
        [EnumMember(Value = "SHADOW")]
        SHADOW,
        [EnumMember(Value = "ETHEREAL")]
        ETHEREAL,
    }
}
