// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The unique identifier of the trait.</summary>
    public enum FactionTraitSymbol {
        [EnumMember(Value = "BUREAUCRATIC")]
        BUREAUCRATIC,
        [EnumMember(Value = "SECRETIVE")]
        SECRETIVE,
        [EnumMember(Value = "CAPITALISTIC")]
        CAPITALISTIC,
        [EnumMember(Value = "INDUSTRIOUS")]
        INDUSTRIOUS,
        [EnumMember(Value = "PEACEFUL")]
        PEACEFUL,
        [EnumMember(Value = "DISTRUSTFUL")]
        DISTRUSTFUL,
        [EnumMember(Value = "WELCOMING")]
        WELCOMING,
        [EnumMember(Value = "SMUGGLERS")]
        SMUGGLERS,
        [EnumMember(Value = "SCAVENGERS")]
        SCAVENGERS,
        [EnumMember(Value = "REBELLIOUS")]
        REBELLIOUS,
        [EnumMember(Value = "EXILES")]
        EXILES,
        [EnumMember(Value = "PIRATES")]
        PIRATES,
        [EnumMember(Value = "RAIDERS")]
        RAIDERS,
        [EnumMember(Value = "CLAN")]
        CLAN,
        [EnumMember(Value = "GUILD")]
        GUILD,
        [EnumMember(Value = "DOMINION")]
        DOMINION,
        [EnumMember(Value = "FRINGE")]
        FRINGE,
        [EnumMember(Value = "FORSAKEN")]
        FORSAKEN,
        [EnumMember(Value = "ISOLATED")]
        ISOLATED,
        [EnumMember(Value = "LOCALIZED")]
        LOCALIZED,
        [EnumMember(Value = "ESTABLISHED")]
        ESTABLISHED,
        [EnumMember(Value = "NOTABLE")]
        NOTABLE,
        [EnumMember(Value = "DOMINANT")]
        DOMINANT,
        [EnumMember(Value = "INESCAPABLE")]
        INESCAPABLE,
        [EnumMember(Value = "INNOVATIVE")]
        INNOVATIVE,
        [EnumMember(Value = "BOLD")]
        BOLD,
        [EnumMember(Value = "VISIONARY")]
        VISIONARY,
        [EnumMember(Value = "CURIOUS")]
        CURIOUS,
        [EnumMember(Value = "DARING")]
        DARING,
        [EnumMember(Value = "EXPLORATORY")]
        EXPLORATORY,
        [EnumMember(Value = "RESOURCEFUL")]
        RESOURCEFUL,
        [EnumMember(Value = "FLEXIBLE")]
        FLEXIBLE,
        [EnumMember(Value = "COOPERATIVE")]
        COOPERATIVE,
        [EnumMember(Value = "UNITED")]
        UNITED,
        [EnumMember(Value = "STRATEGIC")]
        STRATEGIC,
        [EnumMember(Value = "INTELLIGENT")]
        INTELLIGENT,
        [EnumMember(Value = "RESEARCH_FOCUSED")]
        RESEARCH_FOCUSED,
        [EnumMember(Value = "COLLABORATIVE")]
        COLLABORATIVE,
        [EnumMember(Value = "PROGRESSIVE")]
        PROGRESSIVE,
        [EnumMember(Value = "MILITARISTIC")]
        MILITARISTIC,
        [EnumMember(Value = "TECHNOLOGICALLY_ADVANCED")]
        TECHNOLOGICALLY_ADVANCED,
        [EnumMember(Value = "AGGRESSIVE")]
        AGGRESSIVE,
        [EnumMember(Value = "IMPERIALISTIC")]
        IMPERIALISTIC,
        [EnumMember(Value = "TREASURE_HUNTERS")]
        TREASURE_HUNTERS,
        [EnumMember(Value = "DEXTEROUS")]
        DEXTEROUS,
        [EnumMember(Value = "UNPREDICTABLE")]
        UNPREDICTABLE,
        [EnumMember(Value = "BRUTAL")]
        BRUTAL,
        [EnumMember(Value = "FLEETING")]
        FLEETING,
        [EnumMember(Value = "ADAPTABLE")]
        ADAPTABLE,
        [EnumMember(Value = "SELF_SUFFICIENT")]
        SELF_SUFFICIENT,
        [EnumMember(Value = "DEFENSIVE")]
        DEFENSIVE,
        [EnumMember(Value = "PROUD")]
        PROUD,
        [EnumMember(Value = "DIVERSE")]
        DIVERSE,
        [EnumMember(Value = "INDEPENDENT")]
        INDEPENDENT,
        [EnumMember(Value = "SELF_INTERESTED")]
        SELF_INTERESTED,
        [EnumMember(Value = "FRAGMENTED")]
        FRAGMENTED,
        [EnumMember(Value = "COMMERCIAL")]
        COMMERCIAL,
        [EnumMember(Value = "FREE_MARKETS")]
        FREE_MARKETS,
        [EnumMember(Value = "ENTREPRENEURIAL")]
        ENTREPRENEURIAL,
    }
}
