// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The type of trade good (export, import, or exchange).</summary>
    public enum MarketTradeGood_type {
        [EnumMember(Value = "EXPORT")]
        EXPORT,
        [EnumMember(Value = "IMPORT")]
        IMPORT,
        [EnumMember(Value = "EXCHANGE")]
        EXCHANGE,
    }
}
