// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The type of transaction.</summary>
    public enum MarketTransaction_type {
        [EnumMember(Value = "PURCHASE")]
        PURCHASE,
        [EnumMember(Value = "SELL")]
        SELL,
    }
}
