// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>
    /// The ship that was scanned. Details include information about the ship that could be detected by the scanner.
    /// </summary>
    public class ScannedShip : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The engine of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ScannedShip_engine? Engine { get; set; }
#nullable restore
#else
        public ScannedShip_engine Engine { get; set; }
#endif
        /// <summary>The frame of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ScannedShip_frame? Frame { get; set; }
#nullable restore
#else
        public ScannedShip_frame Frame { get; set; }
#endif
        /// <summary>List of mounts installed in the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ScannedShip_mounts>? Mounts { get; set; }
#nullable restore
#else
        public List<ScannedShip_mounts> Mounts { get; set; }
#endif
        /// <summary>The navigation information of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShipNav? Nav { get; set; }
#nullable restore
#else
        public ShipNav Nav { get; set; }
#endif
        /// <summary>The reactor of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ScannedShip_reactor? Reactor { get; set; }
#nullable restore
#else
        public ScannedShip_reactor Reactor { get; set; }
#endif
        /// <summary>The public registration information of the ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShipRegistration? Registration { get; set; }
#nullable restore
#else
        public ShipRegistration Registration { get; set; }
#endif
        /// <summary>The globally unique identifier of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Symbol { get; set; }
#nullable restore
#else
        public string Symbol { get; set; }
#endif
        /// <summary>
        /// Instantiates a new ScannedShip and sets the default values.
        /// </summary>
        public ScannedShip() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ScannedShip CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ScannedShip();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"engine", n => { Engine = n.GetObjectValue<ScannedShip_engine>(ScannedShip_engine.CreateFromDiscriminatorValue); } },
                {"frame", n => { Frame = n.GetObjectValue<ScannedShip_frame>(ScannedShip_frame.CreateFromDiscriminatorValue); } },
                {"mounts", n => { Mounts = n.GetCollectionOfObjectValues<ScannedShip_mounts>(ScannedShip_mounts.CreateFromDiscriminatorValue)?.ToList(); } },
                {"nav", n => { Nav = n.GetObjectValue<ShipNav>(ShipNav.CreateFromDiscriminatorValue); } },
                {"reactor", n => { Reactor = n.GetObjectValue<ScannedShip_reactor>(ScannedShip_reactor.CreateFromDiscriminatorValue); } },
                {"registration", n => { Registration = n.GetObjectValue<ShipRegistration>(ShipRegistration.CreateFromDiscriminatorValue); } },
                {"symbol", n => { Symbol = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ScannedShip_engine>("engine", Engine);
            writer.WriteObjectValue<ScannedShip_frame>("frame", Frame);
            writer.WriteCollectionOfObjectValues<ScannedShip_mounts>("mounts", Mounts);
            writer.WriteObjectValue<ShipNav>("nav", Nav);
            writer.WriteObjectValue<ScannedShip_reactor>("reactor", Reactor);
            writer.WriteObjectValue<ShipRegistration>("registration", Registration);
            writer.WriteStringValue("symbol", Symbol);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
