// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    public enum ShipMount_deposits {
        [EnumMember(Value = "QUARTZ_SAND")]
        QUARTZ_SAND,
        [EnumMember(Value = "SILICON_CRYSTALS")]
        SILICON_CRYSTALS,
        [EnumMember(Value = "PRECIOUS_STONES")]
        PRECIOUS_STONES,
        [EnumMember(Value = "ICE_WATER")]
        ICE_WATER,
        [EnumMember(Value = "AMMONIA_ICE")]
        AMMONIA_ICE,
        [EnumMember(Value = "IRON_ORE")]
        IRON_ORE,
        [EnumMember(Value = "COPPER_ORE")]
        COPPER_ORE,
        [EnumMember(Value = "SILVER_ORE")]
        SILVER_ORE,
        [EnumMember(Value = "ALUMINUM_ORE")]
        ALUMINUM_ORE,
        [EnumMember(Value = "GOLD_ORE")]
        GOLD_ORE,
        [EnumMember(Value = "PLATINUM_ORE")]
        PLATINUM_ORE,
        [EnumMember(Value = "DIAMONDS")]
        DIAMONDS,
        [EnumMember(Value = "URANITE_ORE")]
        URANITE_ORE,
        [EnumMember(Value = "MERITIUM_ORE")]
        MERITIUM_ORE,
    }
}
