// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The current status of the ship</summary>
    public enum ShipNavStatus {
        [EnumMember(Value = "IN_TRANSIT")]
        IN_TRANSIT,
        [EnumMember(Value = "IN_ORBIT")]
        IN_ORBIT,
        [EnumMember(Value = "DOCKED")]
        DOCKED,
    }
}
