// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The symbol of the engine.</summary>
    public enum ShipEngine_symbol {
        [EnumMember(Value = "ENGINE_IMPULSE_DRIVE_I")]
        ENGINE_IMPULSE_DRIVE_I,
        [EnumMember(Value = "ENGINE_ION_DRIVE_I")]
        ENGINE_ION_DRIVE_I,
        [EnumMember(Value = "ENGINE_ION_DRIVE_II")]
        ENGINE_ION_DRIVE_II,
        [EnumMember(Value = "ENGINE_HYPER_DRIVE_I")]
        ENGINE_HYPER_DRIVE_I,
    }
}
