// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>
    /// A mount is installed on the exterier of a ship.
    /// </summary>
    public class ShipMount : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Mounts that have this value denote what goods can be produced from using the mount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ShipMount_deposits?>? Deposits { get; set; }
#nullable restore
#else
        public List<ShipMount_deposits?> Deposits { get; set; }
#endif
        /// <summary>Description of this mount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Name of this mount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The requirements for installation on a ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShipRequirements? Requirements { get; set; }
#nullable restore
#else
        public ShipRequirements Requirements { get; set; }
#endif
        /// <summary>Mounts that have this value, such as mining lasers, denote how powerful this mount&apos;s capabilities are.</summary>
        public int? Strength { get; set; }
        /// <summary>Symbo of this mount.</summary>
        public ShipMount_symbol? Symbol { get; set; }
        /// <summary>
        /// Instantiates a new ShipMount and sets the default values.
        /// </summary>
        public ShipMount() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ShipMount CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ShipMount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"deposits", n => { Deposits = n.GetCollectionOfEnumValues<ShipMount_deposits>()?.ToList(); } },
                {"description", n => { Description = n.GetStringValue(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"requirements", n => { Requirements = n.GetObjectValue<ShipRequirements>(ShipRequirements.CreateFromDiscriminatorValue); } },
                {"strength", n => { Strength = n.GetIntValue(); } },
                {"symbol", n => { Symbol = n.GetEnumValue<ShipMount_symbol>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<ShipMount_deposits>("deposits", Deposits);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<ShipRequirements>("requirements", Requirements);
            writer.WriteIntValue("strength", Strength);
            writer.WriteEnumValue<ShipMount_symbol>("symbol", Symbol);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
