// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The rotation of crew shifts. A stricter shift improves the ship&apos;s performance. A more relaxed shift improves the crew&apos;s morale.</summary>
    public enum ShipCrew_rotation {
        [EnumMember(Value = "STRICT")]
        STRICT,
        [EnumMember(Value = "RELAXED")]
        RELAXED,
    }
}
