// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>Symbo of this mount.</summary>
    public enum ShipMount_symbol {
        [EnumMember(Value = "MOUNT_GAS_SIPHON_I")]
        MOUNT_GAS_SIPHON_I,
        [EnumMember(Value = "MOUNT_GAS_SIPHON_II")]
        MOUNT_GAS_SIPHON_II,
        [EnumMember(Value = "MOUNT_GAS_SIPHON_III")]
        MOUNT_GAS_SIPHON_III,
        [EnumMember(Value = "MOUNT_SURVEYOR_I")]
        MOUNT_SURVEYOR_I,
        [EnumMember(Value = "MOUNT_SURVEYOR_II")]
        MOUNT_SURVEYOR_II,
        [EnumMember(Value = "MOUNT_SURVEYOR_III")]
        MOUNT_SURVEYOR_III,
        [EnumMember(Value = "MOUNT_SENSOR_ARRAY_I")]
        MOUNT_SENSOR_ARRAY_I,
        [EnumMember(Value = "MOUNT_SENSOR_ARRAY_II")]
        MOUNT_SENSOR_ARRAY_II,
        [EnumMember(Value = "MOUNT_SENSOR_ARRAY_III")]
        MOUNT_SENSOR_ARRAY_III,
        [EnumMember(Value = "MOUNT_MINING_LASER_I")]
        MOUNT_MINING_LASER_I,
        [EnumMember(Value = "MOUNT_MINING_LASER_II")]
        MOUNT_MINING_LASER_II,
        [EnumMember(Value = "MOUNT_MINING_LASER_III")]
        MOUNT_MINING_LASER_III,
        [EnumMember(Value = "MOUNT_LASER_CANNON_I")]
        MOUNT_LASER_CANNON_I,
        [EnumMember(Value = "MOUNT_MISSILE_LAUNCHER_I")]
        MOUNT_MISSILE_LAUNCHER_I,
        [EnumMember(Value = "MOUNT_TURRET_I")]
        MOUNT_TURRET_I,
    }
}
