// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>Symbol of the frame.</summary>
    public enum ShipFrame_symbol {
        [EnumMember(Value = "FRAME_PROBE")]
        FRAME_PROBE,
        [EnumMember(Value = "FRAME_DRONE")]
        FRAME_DRONE,
        [EnumMember(Value = "FRAME_INTERCEPTOR")]
        FRAME_INTERCEPTOR,
        [EnumMember(Value = "FRAME_RACER")]
        FRAME_RACER,
        [EnumMember(Value = "FRAME_FIGHTER")]
        FRAME_FIGHTER,
        [EnumMember(Value = "FRAME_FRIGATE")]
        FRAME_FRIGATE,
        [EnumMember(Value = "FRAME_SHUTTLE")]
        FRAME_SHUTTLE,
        [EnumMember(Value = "FRAME_EXPLORER")]
        FRAME_EXPLORER,
        [EnumMember(Value = "FRAME_MINER")]
        FRAME_MINER,
        [EnumMember(Value = "FRAME_LIGHT_FREIGHTER")]
        FRAME_LIGHT_FREIGHTER,
        [EnumMember(Value = "FRAME_HEAVY_FREIGHTER")]
        FRAME_HEAVY_FREIGHTER,
        [EnumMember(Value = "FRAME_TRANSPORT")]
        FRAME_TRANSPORT,
        [EnumMember(Value = "FRAME_DESTROYER")]
        FRAME_DESTROYER,
        [EnumMember(Value = "FRAME_CRUISER")]
        FRAME_CRUISER,
        [EnumMember(Value = "FRAME_CARRIER")]
        FRAME_CARRIER,
    }
}
