// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>Type of ship</summary>
    public enum ShipType {
        [EnumMember(Value = "SHIP_PROBE")]
        SHIP_PROBE,
        [EnumMember(Value = "SHIP_MINING_DRONE")]
        SHIP_MINING_DRONE,
        [EnumMember(Value = "SHIP_SIPHON_DRONE")]
        SHIP_SIPHON_DRONE,
        [EnumMember(Value = "SHIP_INTERCEPTOR")]
        SHIP_INTERCEPTOR,
        [EnumMember(Value = "SHIP_LIGHT_HAULER")]
        SHIP_LIGHT_HAULER,
        [EnumMember(Value = "SHIP_COMMAND_FRIGATE")]
        SHIP_COMMAND_FRIGATE,
        [EnumMember(Value = "SHIP_EXPLORER")]
        SHIP_EXPLORER,
        [EnumMember(Value = "SHIP_HEAVY_FREIGHTER")]
        SHIP_HEAVY_FREIGHTER,
        [EnumMember(Value = "SHIP_LIGHT_SHUTTLE")]
        SHIP_LIGHT_SHUTTLE,
        [EnumMember(Value = "SHIP_ORE_HOUND")]
        SHIP_ORE_HOUND,
        [EnumMember(Value = "SHIP_REFINING_FREIGHTER")]
        SHIP_REFINING_FREIGHTER,
        [EnumMember(Value = "SHIP_SURVEYOR")]
        SHIP_SURVEYOR,
    }
}
