// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The ship&apos;s set speed when traveling between waypoints or systems.</summary>
    public enum ShipNavFlightMode {
        [EnumMember(Value = "DRIFT")]
        DRIFT,
        [EnumMember(Value = "STEALTH")]
        STEALTH,
        [EnumMember(Value = "CRUISE")]
        CRUISE,
        [EnumMember(Value = "BURN")]
        BURN,
    }
}
