// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>
    /// The ship&apos;s crew service and maintain the ship&apos;s systems and equipment.
    /// </summary>
    public class ShipCrew : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The maximum number of crew members the ship can support.</summary>
        public int? Capacity { get; set; }
        /// <summary>The current number of crew members on the ship.</summary>
        public int? Current { get; set; }
        /// <summary>A rough measure of the crew&apos;s morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.</summary>
        public int? Morale { get; set; }
        /// <summary>The minimum number of crew members required to maintain the ship.</summary>
        public int? Required { get; set; }
        /// <summary>The rotation of crew shifts. A stricter shift improves the ship&apos;s performance. A more relaxed shift improves the crew&apos;s morale.</summary>
        public ShipCrew_rotation? Rotation { get; set; }
        /// <summary>The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.</summary>
        public int? Wages { get; set; }
        /// <summary>
        /// Instantiates a new ShipCrew and sets the default values.
        /// </summary>
        public ShipCrew() {
            AdditionalData = new Dictionary<string, object>();
            Rotation = ShipCrew_rotation.STRICT;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ShipCrew CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ShipCrew();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"capacity", n => { Capacity = n.GetIntValue(); } },
                {"current", n => { Current = n.GetIntValue(); } },
                {"morale", n => { Morale = n.GetIntValue(); } },
                {"required", n => { Required = n.GetIntValue(); } },
                {"rotation", n => { Rotation = n.GetEnumValue<ShipCrew_rotation>(); } },
                {"wages", n => { Wages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("capacity", Capacity);
            writer.WriteIntValue("current", Current);
            writer.WriteIntValue("morale", Morale);
            writer.WriteIntValue("required", Required);
            writer.WriteEnumValue<ShipCrew_rotation>("rotation", Rotation);
            writer.WriteIntValue("wages", Wages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
