// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The registered role of the ship</summary>
    public enum ShipRole {
        [EnumMember(Value = "FABRICATOR")]
        FABRICATOR,
        [EnumMember(Value = "HARVESTER")]
        HARVESTER,
        [EnumMember(Value = "HAULER")]
        HAULER,
        [EnumMember(Value = "INTERCEPTOR")]
        INTERCEPTOR,
        [EnumMember(Value = "EXCAVATOR")]
        EXCAVATOR,
        [EnumMember(Value = "TRANSPORT")]
        TRANSPORT,
        [EnumMember(Value = "REPAIR")]
        REPAIR,
        [EnumMember(Value = "SURVEYOR")]
        SURVEYOR,
        [EnumMember(Value = "COMMAND")]
        COMMAND,
        [EnumMember(Value = "CARRIER")]
        CARRIER,
        [EnumMember(Value = "PATROL")]
        PATROL,
        [EnumMember(Value = "SATELLITE")]
        SATELLITE,
        [EnumMember(Value = "EXPLORER")]
        EXPLORER,
        [EnumMember(Value = "REFINERY")]
        REFINERY,
    }
}
