// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SpaceTraders.Client.Models {
    public class ShipyardShip : IAdditionalDataHolder, IParsable {
        /// <summary>The activity level of a trade good. If the good is an import, this represents how strong consumption is. If the good is an export, this represents how strong the production is for the good. When activity is strong, consumption or production is near maximum capacity. When activity is weak, consumption or production is near minimum capacity.</summary>
        public ActivityLevel? Activity { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The crew property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShipyardShip_crew? Crew { get; set; }
#nullable restore
#else
        public ShipyardShip_crew Crew { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The engine determines how quickly a ship travels between waypoints.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShipEngine? Engine { get; set; }
#nullable restore
#else
        public ShipEngine Engine { get; set; }
#endif
        /// <summary>The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShipFrame? Frame { get; set; }
#nullable restore
#else
        public ShipFrame Frame { get; set; }
#endif
        /// <summary>The modules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ShipModule>? Modules { get; set; }
#nullable restore
#else
        public List<ShipModule> Modules { get; set; }
#endif
        /// <summary>The mounts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ShipMount>? Mounts { get; set; }
#nullable restore
#else
        public List<ShipMount> Mounts { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The purchasePrice property</summary>
        public int? PurchasePrice { get; set; }
        /// <summary>The reactor of the ship. The reactor is responsible for powering the ship&apos;s systems and weapons.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShipReactor? Reactor { get; set; }
#nullable restore
#else
        public ShipReactor Reactor { get; set; }
#endif
        /// <summary>The supply level of a trade good.</summary>
        public SupplyLevel? Supply { get; set; }
        /// <summary>Type of ship</summary>
        public ShipType? Type { get; set; }
        /// <summary>
        /// Instantiates a new ShipyardShip and sets the default values.
        /// </summary>
        public ShipyardShip() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ShipyardShip CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ShipyardShip();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"activity", n => { Activity = n.GetEnumValue<ActivityLevel>(); } },
                {"crew", n => { Crew = n.GetObjectValue<ShipyardShip_crew>(ShipyardShip_crew.CreateFromDiscriminatorValue); } },
                {"description", n => { Description = n.GetStringValue(); } },
                {"engine", n => { Engine = n.GetObjectValue<ShipEngine>(ShipEngine.CreateFromDiscriminatorValue); } },
                {"frame", n => { Frame = n.GetObjectValue<ShipFrame>(ShipFrame.CreateFromDiscriminatorValue); } },
                {"modules", n => { Modules = n.GetCollectionOfObjectValues<ShipModule>(ShipModule.CreateFromDiscriminatorValue)?.ToList(); } },
                {"mounts", n => { Mounts = n.GetCollectionOfObjectValues<ShipMount>(ShipMount.CreateFromDiscriminatorValue)?.ToList(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"purchasePrice", n => { PurchasePrice = n.GetIntValue(); } },
                {"reactor", n => { Reactor = n.GetObjectValue<ShipReactor>(ShipReactor.CreateFromDiscriminatorValue); } },
                {"supply", n => { Supply = n.GetEnumValue<SupplyLevel>(); } },
                {"type", n => { Type = n.GetEnumValue<ShipType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<ActivityLevel>("activity", Activity);
            writer.WriteObjectValue<ShipyardShip_crew>("crew", Crew);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<ShipEngine>("engine", Engine);
            writer.WriteObjectValue<ShipFrame>("frame", Frame);
            writer.WriteCollectionOfObjectValues<ShipModule>("modules", Modules);
            writer.WriteCollectionOfObjectValues<ShipMount>("mounts", Mounts);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("purchasePrice", PurchasePrice);
            writer.WriteObjectValue<ShipReactor>("reactor", Reactor);
            writer.WriteEnumValue<SupplyLevel>("supply", Supply);
            writer.WriteEnumValue<ShipType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
