// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>Symbol of the reactor.</summary>
    public enum ShipReactor_symbol {
        [EnumMember(Value = "REACTOR_SOLAR_I")]
        REACTOR_SOLAR_I,
        [EnumMember(Value = "REACTOR_FUSION_I")]
        REACTOR_FUSION_I,
        [EnumMember(Value = "REACTOR_FISSION_I")]
        REACTOR_FISSION_I,
        [EnumMember(Value = "REACTOR_CHEMICAL_I")]
        REACTOR_CHEMICAL_I,
        [EnumMember(Value = "REACTOR_ANTIMATTER_I")]
        REACTOR_ANTIMATTER_I,
    }
}
