// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The symbol of the module.</summary>
    public enum ShipModule_symbol {
        [EnumMember(Value = "MODULE_MINERAL_PROCESSOR_I")]
        MODULE_MINERAL_PROCESSOR_I,
        [EnumMember(Value = "MODULE_GAS_PROCESSOR_I")]
        MODULE_GAS_PROCESSOR_I,
        [EnumMember(Value = "MODULE_CARGO_HOLD_I")]
        MODULE_CARGO_HOLD_I,
        [EnumMember(Value = "MODULE_CARGO_HOLD_II")]
        MODULE_CARGO_HOLD_II,
        [EnumMember(Value = "MODULE_CARGO_HOLD_III")]
        MODULE_CARGO_HOLD_III,
        [EnumMember(Value = "MODULE_CREW_QUARTERS_I")]
        MODULE_CREW_QUARTERS_I,
        [EnumMember(Value = "MODULE_ENVOY_QUARTERS_I")]
        MODULE_ENVOY_QUARTERS_I,
        [EnumMember(Value = "MODULE_PASSENGER_CABIN_I")]
        MODULE_PASSENGER_CABIN_I,
        [EnumMember(Value = "MODULE_MICRO_REFINERY_I")]
        MODULE_MICRO_REFINERY_I,
        [EnumMember(Value = "MODULE_ORE_REFINERY_I")]
        MODULE_ORE_REFINERY_I,
        [EnumMember(Value = "MODULE_FUEL_REFINERY_I")]
        MODULE_FUEL_REFINERY_I,
        [EnumMember(Value = "MODULE_SCIENCE_LAB_I")]
        MODULE_SCIENCE_LAB_I,
        [EnumMember(Value = "MODULE_JUMP_DRIVE_I")]
        MODULE_JUMP_DRIVE_I,
        [EnumMember(Value = "MODULE_JUMP_DRIVE_II")]
        MODULE_JUMP_DRIVE_II,
        [EnumMember(Value = "MODULE_JUMP_DRIVE_III")]
        MODULE_JUMP_DRIVE_III,
        [EnumMember(Value = "MODULE_WARP_DRIVE_I")]
        MODULE_WARP_DRIVE_I,
        [EnumMember(Value = "MODULE_WARP_DRIVE_II")]
        MODULE_WARP_DRIVE_II,
        [EnumMember(Value = "MODULE_WARP_DRIVE_III")]
        MODULE_WARP_DRIVE_III,
        [EnumMember(Value = "MODULE_SHIELD_GENERATOR_I")]
        MODULE_SHIELD_GENERATOR_I,
        [EnumMember(Value = "MODULE_SHIELD_GENERATOR_II")]
        MODULE_SHIELD_GENERATOR_II,
    }
}
