// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>
    /// Details of the ship&apos;s fuel tanks including how much fuel was consumed during the last transit or action.
    /// </summary>
    public class ShipFuel : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The maximum amount of fuel the ship&apos;s tanks can hold.</summary>
        public int? Capacity { get; set; }
        /// <summary>An object that only shows up when an action has consumed fuel in the process. Shows the fuel consumption data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShipFuel_consumed? Consumed { get; set; }
#nullable restore
#else
        public ShipFuel_consumed Consumed { get; set; }
#endif
        /// <summary>The current amount of fuel in the ship&apos;s tanks.</summary>
        public int? Current { get; set; }
        /// <summary>
        /// Instantiates a new ShipFuel and sets the default values.
        /// </summary>
        public ShipFuel() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ShipFuel CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ShipFuel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"capacity", n => { Capacity = n.GetIntValue(); } },
                {"consumed", n => { Consumed = n.GetObjectValue<ShipFuel_consumed>(ShipFuel_consumed.CreateFromDiscriminatorValue); } },
                {"current", n => { Current = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("capacity", Capacity);
            writer.WriteObjectValue<ShipFuel_consumed>("consumed", Consumed);
            writer.WriteIntValue("current", Current);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
