// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The supply level of a trade good.</summary>
    public enum SupplyLevel {
        [EnumMember(Value = "SCARCE")]
        SCARCE,
        [EnumMember(Value = "LIMITED")]
        LIMITED,
        [EnumMember(Value = "MODERATE")]
        MODERATE,
        [EnumMember(Value = "HIGH")]
        HIGH,
        [EnumMember(Value = "ABUNDANT")]
        ABUNDANT,
    }
}
