// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The type of system.</summary>
    public enum SystemType {
        [EnumMember(Value = "NEUTRON_STAR")]
        NEUTRON_STAR,
        [EnumMember(Value = "RED_STAR")]
        RED_STAR,
        [EnumMember(Value = "ORANGE_STAR")]
        ORANGE_STAR,
        [EnumMember(Value = "BLUE_STAR")]
        BLUE_STAR,
        [EnumMember(Value = "YOUNG_STAR")]
        YOUNG_STAR,
        [EnumMember(Value = "WHITE_DWARF")]
        WHITE_DWARF,
        [EnumMember(Value = "BLACK_HOLE")]
        BLACK_HOLE,
        [EnumMember(Value = "HYPERGIANT")]
        HYPERGIANT,
        [EnumMember(Value = "NEBULA")]
        NEBULA,
        [EnumMember(Value = "UNSTABLE")]
        UNSTABLE,
    }
}
