// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The good&apos;s symbol.</summary>
    public enum TradeSymbol {
        [EnumMember(Value = "PRECIOUS_STONES")]
        PRECIOUS_STONES,
        [EnumMember(Value = "QUARTZ_SAND")]
        QUARTZ_SAND,
        [EnumMember(Value = "SILICON_CRYSTALS")]
        SILICON_CRYSTALS,
        [EnumMember(Value = "AMMONIA_ICE")]
        AMMONIA_ICE,
        [EnumMember(Value = "LIQUID_HYDROGEN")]
        LIQUID_HYDROGEN,
        [EnumMember(Value = "LIQUID_NITROGEN")]
        LIQUID_NITROGEN,
        [EnumMember(Value = "ICE_WATER")]
        ICE_WATER,
        [EnumMember(Value = "EXOTIC_MATTER")]
        EXOTIC_MATTER,
        [EnumMember(Value = "ADVANCED_CIRCUITRY")]
        ADVANCED_CIRCUITRY,
        [EnumMember(Value = "GRAVITON_EMITTERS")]
        GRAVITON_EMITTERS,
        [EnumMember(Value = "IRON")]
        IRON,
        [EnumMember(Value = "IRON_ORE")]
        IRON_ORE,
        [EnumMember(Value = "COPPER")]
        COPPER,
        [EnumMember(Value = "COPPER_ORE")]
        COPPER_ORE,
        [EnumMember(Value = "ALUMINUM")]
        ALUMINUM,
        [EnumMember(Value = "ALUMINUM_ORE")]
        ALUMINUM_ORE,
        [EnumMember(Value = "SILVER")]
        SILVER,
        [EnumMember(Value = "SILVER_ORE")]
        SILVER_ORE,
        [EnumMember(Value = "GOLD")]
        GOLD,
        [EnumMember(Value = "GOLD_ORE")]
        GOLD_ORE,
        [EnumMember(Value = "PLATINUM")]
        PLATINUM,
        [EnumMember(Value = "PLATINUM_ORE")]
        PLATINUM_ORE,
        [EnumMember(Value = "DIAMONDS")]
        DIAMONDS,
        [EnumMember(Value = "URANITE")]
        URANITE,
        [EnumMember(Value = "URANITE_ORE")]
        URANITE_ORE,
        [EnumMember(Value = "MERITIUM")]
        MERITIUM,
        [EnumMember(Value = "MERITIUM_ORE")]
        MERITIUM_ORE,
        [EnumMember(Value = "HYDROCARBON")]
        HYDROCARBON,
        [EnumMember(Value = "ANTIMATTER")]
        ANTIMATTER,
        [EnumMember(Value = "FAB_MATS")]
        FAB_MATS,
        [EnumMember(Value = "FERTILIZERS")]
        FERTILIZERS,
        [EnumMember(Value = "FABRICS")]
        FABRICS,
        [EnumMember(Value = "FOOD")]
        FOOD,
        [EnumMember(Value = "JEWELRY")]
        JEWELRY,
        [EnumMember(Value = "MACHINERY")]
        MACHINERY,
        [EnumMember(Value = "FIREARMS")]
        FIREARMS,
        [EnumMember(Value = "ASSAULT_RIFLES")]
        ASSAULT_RIFLES,
        [EnumMember(Value = "MILITARY_EQUIPMENT")]
        MILITARY_EQUIPMENT,
        [EnumMember(Value = "EXPLOSIVES")]
        EXPLOSIVES,
        [EnumMember(Value = "LAB_INSTRUMENTS")]
        LAB_INSTRUMENTS,
        [EnumMember(Value = "AMMUNITION")]
        AMMUNITION,
        [EnumMember(Value = "ELECTRONICS")]
        ELECTRONICS,
        [EnumMember(Value = "SHIP_PLATING")]
        SHIP_PLATING,
        [EnumMember(Value = "SHIP_PARTS")]
        SHIP_PARTS,
        [EnumMember(Value = "EQUIPMENT")]
        EQUIPMENT,
        [EnumMember(Value = "FUEL")]
        FUEL,
        [EnumMember(Value = "MEDICINE")]
        MEDICINE,
        [EnumMember(Value = "DRUGS")]
        DRUGS,
        [EnumMember(Value = "CLOTHING")]
        CLOTHING,
        [EnumMember(Value = "MICROPROCESSORS")]
        MICROPROCESSORS,
        [EnumMember(Value = "PLASTICS")]
        PLASTICS,
        [EnumMember(Value = "POLYNUCLEOTIDES")]
        POLYNUCLEOTIDES,
        [EnumMember(Value = "BIOCOMPOSITES")]
        BIOCOMPOSITES,
        [EnumMember(Value = "QUANTUM_STABILIZERS")]
        QUANTUM_STABILIZERS,
        [EnumMember(Value = "NANOBOTS")]
        NANOBOTS,
        [EnumMember(Value = "AI_MAINFRAMES")]
        AI_MAINFRAMES,
        [EnumMember(Value = "QUANTUM_DRIVES")]
        QUANTUM_DRIVES,
        [EnumMember(Value = "ROBOTIC_DRONES")]
        ROBOTIC_DRONES,
        [EnumMember(Value = "CYBER_IMPLANTS")]
        CYBER_IMPLANTS,
        [EnumMember(Value = "GENE_THERAPEUTICS")]
        GENE_THERAPEUTICS,
        [EnumMember(Value = "NEURAL_CHIPS")]
        NEURAL_CHIPS,
        [EnumMember(Value = "MOOD_REGULATORS")]
        MOOD_REGULATORS,
        [EnumMember(Value = "VIRAL_AGENTS")]
        VIRAL_AGENTS,
        [EnumMember(Value = "MICRO_FUSION_GENERATORS")]
        MICRO_FUSION_GENERATORS,
        [EnumMember(Value = "SUPERGRAINS")]
        SUPERGRAINS,
        [EnumMember(Value = "LASER_RIFLES")]
        LASER_RIFLES,
        [EnumMember(Value = "HOLOGRAPHICS")]
        HOLOGRAPHICS,
        [EnumMember(Value = "SHIP_SALVAGE")]
        SHIP_SALVAGE,
        [EnumMember(Value = "RELIC_TECH")]
        RELIC_TECH,
        [EnumMember(Value = "NOVEL_LIFEFORMS")]
        NOVEL_LIFEFORMS,
        [EnumMember(Value = "BOTANICAL_SPECIMENS")]
        BOTANICAL_SPECIMENS,
        [EnumMember(Value = "CULTURAL_ARTIFACTS")]
        CULTURAL_ARTIFACTS,
        [EnumMember(Value = "FRAME_PROBE")]
        FRAME_PROBE,
        [EnumMember(Value = "FRAME_DRONE")]
        FRAME_DRONE,
        [EnumMember(Value = "FRAME_INTERCEPTOR")]
        FRAME_INTERCEPTOR,
        [EnumMember(Value = "FRAME_RACER")]
        FRAME_RACER,
        [EnumMember(Value = "FRAME_FIGHTER")]
        FRAME_FIGHTER,
        [EnumMember(Value = "FRAME_FRIGATE")]
        FRAME_FRIGATE,
        [EnumMember(Value = "FRAME_SHUTTLE")]
        FRAME_SHUTTLE,
        [EnumMember(Value = "FRAME_EXPLORER")]
        FRAME_EXPLORER,
        [EnumMember(Value = "FRAME_MINER")]
        FRAME_MINER,
        [EnumMember(Value = "FRAME_LIGHT_FREIGHTER")]
        FRAME_LIGHT_FREIGHTER,
        [EnumMember(Value = "FRAME_HEAVY_FREIGHTER")]
        FRAME_HEAVY_FREIGHTER,
        [EnumMember(Value = "FRAME_TRANSPORT")]
        FRAME_TRANSPORT,
        [EnumMember(Value = "FRAME_DESTROYER")]
        FRAME_DESTROYER,
        [EnumMember(Value = "FRAME_CRUISER")]
        FRAME_CRUISER,
        [EnumMember(Value = "FRAME_CARRIER")]
        FRAME_CARRIER,
        [EnumMember(Value = "REACTOR_SOLAR_I")]
        REACTOR_SOLAR_I,
        [EnumMember(Value = "REACTOR_FUSION_I")]
        REACTOR_FUSION_I,
        [EnumMember(Value = "REACTOR_FISSION_I")]
        REACTOR_FISSION_I,
        [EnumMember(Value = "REACTOR_CHEMICAL_I")]
        REACTOR_CHEMICAL_I,
        [EnumMember(Value = "REACTOR_ANTIMATTER_I")]
        REACTOR_ANTIMATTER_I,
        [EnumMember(Value = "ENGINE_IMPULSE_DRIVE_I")]
        ENGINE_IMPULSE_DRIVE_I,
        [EnumMember(Value = "ENGINE_ION_DRIVE_I")]
        ENGINE_ION_DRIVE_I,
        [EnumMember(Value = "ENGINE_ION_DRIVE_II")]
        ENGINE_ION_DRIVE_II,
        [EnumMember(Value = "ENGINE_HYPER_DRIVE_I")]
        ENGINE_HYPER_DRIVE_I,
        [EnumMember(Value = "MODULE_MINERAL_PROCESSOR_I")]
        MODULE_MINERAL_PROCESSOR_I,
        [EnumMember(Value = "MODULE_GAS_PROCESSOR_I")]
        MODULE_GAS_PROCESSOR_I,
        [EnumMember(Value = "MODULE_CARGO_HOLD_I")]
        MODULE_CARGO_HOLD_I,
        [EnumMember(Value = "MODULE_CARGO_HOLD_II")]
        MODULE_CARGO_HOLD_II,
        [EnumMember(Value = "MODULE_CARGO_HOLD_III")]
        MODULE_CARGO_HOLD_III,
        [EnumMember(Value = "MODULE_CREW_QUARTERS_I")]
        MODULE_CREW_QUARTERS_I,
        [EnumMember(Value = "MODULE_ENVOY_QUARTERS_I")]
        MODULE_ENVOY_QUARTERS_I,
        [EnumMember(Value = "MODULE_PASSENGER_CABIN_I")]
        MODULE_PASSENGER_CABIN_I,
        [EnumMember(Value = "MODULE_MICRO_REFINERY_I")]
        MODULE_MICRO_REFINERY_I,
        [EnumMember(Value = "MODULE_SCIENCE_LAB_I")]
        MODULE_SCIENCE_LAB_I,
        [EnumMember(Value = "MODULE_JUMP_DRIVE_I")]
        MODULE_JUMP_DRIVE_I,
        [EnumMember(Value = "MODULE_JUMP_DRIVE_II")]
        MODULE_JUMP_DRIVE_II,
        [EnumMember(Value = "MODULE_JUMP_DRIVE_III")]
        MODULE_JUMP_DRIVE_III,
        [EnumMember(Value = "MODULE_WARP_DRIVE_I")]
        MODULE_WARP_DRIVE_I,
        [EnumMember(Value = "MODULE_WARP_DRIVE_II")]
        MODULE_WARP_DRIVE_II,
        [EnumMember(Value = "MODULE_WARP_DRIVE_III")]
        MODULE_WARP_DRIVE_III,
        [EnumMember(Value = "MODULE_SHIELD_GENERATOR_I")]
        MODULE_SHIELD_GENERATOR_I,
        [EnumMember(Value = "MODULE_SHIELD_GENERATOR_II")]
        MODULE_SHIELD_GENERATOR_II,
        [EnumMember(Value = "MODULE_ORE_REFINERY_I")]
        MODULE_ORE_REFINERY_I,
        [EnumMember(Value = "MODULE_FUEL_REFINERY_I")]
        MODULE_FUEL_REFINERY_I,
        [EnumMember(Value = "MOUNT_GAS_SIPHON_I")]
        MOUNT_GAS_SIPHON_I,
        [EnumMember(Value = "MOUNT_GAS_SIPHON_II")]
        MOUNT_GAS_SIPHON_II,
        [EnumMember(Value = "MOUNT_GAS_SIPHON_III")]
        MOUNT_GAS_SIPHON_III,
        [EnumMember(Value = "MOUNT_SURVEYOR_I")]
        MOUNT_SURVEYOR_I,
        [EnumMember(Value = "MOUNT_SURVEYOR_II")]
        MOUNT_SURVEYOR_II,
        [EnumMember(Value = "MOUNT_SURVEYOR_III")]
        MOUNT_SURVEYOR_III,
        [EnumMember(Value = "MOUNT_SENSOR_ARRAY_I")]
        MOUNT_SENSOR_ARRAY_I,
        [EnumMember(Value = "MOUNT_SENSOR_ARRAY_II")]
        MOUNT_SENSOR_ARRAY_II,
        [EnumMember(Value = "MOUNT_SENSOR_ARRAY_III")]
        MOUNT_SENSOR_ARRAY_III,
        [EnumMember(Value = "MOUNT_MINING_LASER_I")]
        MOUNT_MINING_LASER_I,
        [EnumMember(Value = "MOUNT_MINING_LASER_II")]
        MOUNT_MINING_LASER_II,
        [EnumMember(Value = "MOUNT_MINING_LASER_III")]
        MOUNT_MINING_LASER_III,
        [EnumMember(Value = "MOUNT_LASER_CANNON_I")]
        MOUNT_LASER_CANNON_I,
        [EnumMember(Value = "MOUNT_MISSILE_LAUNCHER_I")]
        MOUNT_MISSILE_LAUNCHER_I,
        [EnumMember(Value = "MOUNT_TURRET_I")]
        MOUNT_TURRET_I,
        [EnumMember(Value = "SHIP_PROBE")]
        SHIP_PROBE,
        [EnumMember(Value = "SHIP_MINING_DRONE")]
        SHIP_MINING_DRONE,
        [EnumMember(Value = "SHIP_SIPHON_DRONE")]
        SHIP_SIPHON_DRONE,
        [EnumMember(Value = "SHIP_INTERCEPTOR")]
        SHIP_INTERCEPTOR,
        [EnumMember(Value = "SHIP_LIGHT_HAULER")]
        SHIP_LIGHT_HAULER,
        [EnumMember(Value = "SHIP_COMMAND_FRIGATE")]
        SHIP_COMMAND_FRIGATE,
        [EnumMember(Value = "SHIP_EXPLORER")]
        SHIP_EXPLORER,
        [EnumMember(Value = "SHIP_HEAVY_FREIGHTER")]
        SHIP_HEAVY_FREIGHTER,
        [EnumMember(Value = "SHIP_LIGHT_SHUTTLE")]
        SHIP_LIGHT_SHUTTLE,
        [EnumMember(Value = "SHIP_ORE_HOUND")]
        SHIP_ORE_HOUND,
        [EnumMember(Value = "SHIP_REFINING_FREIGHTER")]
        SHIP_REFINING_FREIGHTER,
        [EnumMember(Value = "SHIP_SURVEYOR")]
        SHIP_SURVEYOR,
    }
}
