// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The unique identifier of the modifier.</summary>
    public enum WaypointModifierSymbol {
        [EnumMember(Value = "STRIPPED")]
        STRIPPED,
        [EnumMember(Value = "UNSTABLE")]
        UNSTABLE,
        [EnumMember(Value = "RADIATION_LEAK")]
        RADIATION_LEAK,
        [EnumMember(Value = "CRITICAL_LIMIT")]
        CRITICAL_LIMIT,
        [EnumMember(Value = "CIVIL_UNREST")]
        CIVIL_UNREST,
    }
}
