// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The unique identifier of the trait.</summary>
    public enum WaypointTraitSymbol {
        [EnumMember(Value = "UNCHARTED")]
        UNCHARTED,
        [EnumMember(Value = "UNDER_CONSTRUCTION")]
        UNDER_CONSTRUCTION,
        [EnumMember(Value = "MARKETPLACE")]
        MARKETPLACE,
        [EnumMember(Value = "SHIPYARD")]
        SHIPYARD,
        [EnumMember(Value = "OUTPOST")]
        OUTPOST,
        [EnumMember(Value = "SCATTERED_SETTLEMENTS")]
        SCATTERED_SETTLEMENTS,
        [EnumMember(Value = "SPRAWLING_CITIES")]
        SPRAWLING_CITIES,
        [EnumMember(Value = "MEGA_STRUCTURES")]
        MEGA_STRUCTURES,
        [EnumMember(Value = "PIRATE_BASE")]
        PIRATE_BASE,
        [EnumMember(Value = "OVERCROWDED")]
        OVERCROWDED,
        [EnumMember(Value = "HIGH_TECH")]
        HIGH_TECH,
        [EnumMember(Value = "CORRUPT")]
        CORRUPT,
        [EnumMember(Value = "BUREAUCRATIC")]
        BUREAUCRATIC,
        [EnumMember(Value = "TRADING_HUB")]
        TRADING_HUB,
        [EnumMember(Value = "INDUSTRIAL")]
        INDUSTRIAL,
        [EnumMember(Value = "BLACK_MARKET")]
        BLACK_MARKET,
        [EnumMember(Value = "RESEARCH_FACILITY")]
        RESEARCH_FACILITY,
        [EnumMember(Value = "MILITARY_BASE")]
        MILITARY_BASE,
        [EnumMember(Value = "SURVEILLANCE_OUTPOST")]
        SURVEILLANCE_OUTPOST,
        [EnumMember(Value = "EXPLORATION_OUTPOST")]
        EXPLORATION_OUTPOST,
        [EnumMember(Value = "MINERAL_DEPOSITS")]
        MINERAL_DEPOSITS,
        [EnumMember(Value = "COMMON_METAL_DEPOSITS")]
        COMMON_METAL_DEPOSITS,
        [EnumMember(Value = "PRECIOUS_METAL_DEPOSITS")]
        PRECIOUS_METAL_DEPOSITS,
        [EnumMember(Value = "RARE_METAL_DEPOSITS")]
        RARE_METAL_DEPOSITS,
        [EnumMember(Value = "METHANE_POOLS")]
        METHANE_POOLS,
        [EnumMember(Value = "ICE_CRYSTALS")]
        ICE_CRYSTALS,
        [EnumMember(Value = "EXPLOSIVE_GASES")]
        EXPLOSIVE_GASES,
        [EnumMember(Value = "STRONG_MAGNETOSPHERE")]
        STRONG_MAGNETOSPHERE,
        [EnumMember(Value = "VIBRANT_AURORAS")]
        VIBRANT_AURORAS,
        [EnumMember(Value = "SALT_FLATS")]
        SALT_FLATS,
        [EnumMember(Value = "CANYONS")]
        CANYONS,
        [EnumMember(Value = "PERPETUAL_DAYLIGHT")]
        PERPETUAL_DAYLIGHT,
        [EnumMember(Value = "PERPETUAL_OVERCAST")]
        PERPETUAL_OVERCAST,
        [EnumMember(Value = "DRY_SEABEDS")]
        DRY_SEABEDS,
        [EnumMember(Value = "MAGMA_SEAS")]
        MAGMA_SEAS,
        [EnumMember(Value = "SUPERVOLCANOES")]
        SUPERVOLCANOES,
        [EnumMember(Value = "ASH_CLOUDS")]
        ASH_CLOUDS,
        [EnumMember(Value = "VAST_RUINS")]
        VAST_RUINS,
        [EnumMember(Value = "MUTATED_FLORA")]
        MUTATED_FLORA,
        [EnumMember(Value = "TERRAFORMED")]
        TERRAFORMED,
        [EnumMember(Value = "EXTREME_TEMPERATURES")]
        EXTREME_TEMPERATURES,
        [EnumMember(Value = "EXTREME_PRESSURE")]
        EXTREME_PRESSURE,
        [EnumMember(Value = "DIVERSE_LIFE")]
        DIVERSE_LIFE,
        [EnumMember(Value = "SCARCE_LIFE")]
        SCARCE_LIFE,
        [EnumMember(Value = "FOSSILS")]
        FOSSILS,
        [EnumMember(Value = "WEAK_GRAVITY")]
        WEAK_GRAVITY,
        [EnumMember(Value = "STRONG_GRAVITY")]
        STRONG_GRAVITY,
        [EnumMember(Value = "CRUSHING_GRAVITY")]
        CRUSHING_GRAVITY,
        [EnumMember(Value = "TOXIC_ATMOSPHERE")]
        TOXIC_ATMOSPHERE,
        [EnumMember(Value = "CORROSIVE_ATMOSPHERE")]
        CORROSIVE_ATMOSPHERE,
        [EnumMember(Value = "BREATHABLE_ATMOSPHERE")]
        BREATHABLE_ATMOSPHERE,
        [EnumMember(Value = "THIN_ATMOSPHERE")]
        THIN_ATMOSPHERE,
        [EnumMember(Value = "JOVIAN")]
        JOVIAN,
        [EnumMember(Value = "ROCKY")]
        ROCKY,
        [EnumMember(Value = "VOLCANIC")]
        VOLCANIC,
        [EnumMember(Value = "FROZEN")]
        FROZEN,
        [EnumMember(Value = "SWAMP")]
        SWAMP,
        [EnumMember(Value = "BARREN")]
        BARREN,
        [EnumMember(Value = "TEMPERATE")]
        TEMPERATE,
        [EnumMember(Value = "JUNGLE")]
        JUNGLE,
        [EnumMember(Value = "OCEAN")]
        OCEAN,
        [EnumMember(Value = "RADIOACTIVE")]
        RADIOACTIVE,
        [EnumMember(Value = "MICRO_GRAVITY_ANOMALIES")]
        MICRO_GRAVITY_ANOMALIES,
        [EnumMember(Value = "DEBRIS_CLUSTER")]
        DEBRIS_CLUSTER,
        [EnumMember(Value = "DEEP_CRATERS")]
        DEEP_CRATERS,
        [EnumMember(Value = "SHALLOW_CRATERS")]
        SHALLOW_CRATERS,
        [EnumMember(Value = "UNSTABLE_COMPOSITION")]
        UNSTABLE_COMPOSITION,
        [EnumMember(Value = "HOLLOWED_INTERIOR")]
        HOLLOWED_INTERIOR,
        [EnumMember(Value = "STRIPPED")]
        STRIPPED,
    }
}
