// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Client.Models {
    /// <summary>The type of waypoint.</summary>
    public enum WaypointType {
        [EnumMember(Value = "PLANET")]
        PLANET,
        [EnumMember(Value = "GAS_GIANT")]
        GAS_GIANT,
        [EnumMember(Value = "MOON")]
        MOON,
        [EnumMember(Value = "ORBITAL_STATION")]
        ORBITAL_STATION,
        [EnumMember(Value = "JUMP_GATE")]
        JUMP_GATE,
        [EnumMember(Value = "ASTEROID_FIELD")]
        ASTEROID_FIELD,
        [EnumMember(Value = "ASTEROID")]
        ASTEROID,
        [EnumMember(Value = "ENGINEERED_ASTEROID")]
        ENGINEERED_ASTEROID,
        [EnumMember(Value = "ASTEROID_BASE")]
        ASTEROID_BASE,
        [EnumMember(Value = "NEBULA")]
        NEBULA,
        [EnumMember(Value = "DEBRIS_FIELD")]
        DEBRIS_FIELD,
        [EnumMember(Value = "GRAVITY_WELL")]
        GRAVITY_WELL,
        [EnumMember(Value = "ARTIFICIAL_GRAVITY_WELL")]
        ARTIFICIAL_GRAVITY_WELL,
        [EnumMember(Value = "FUEL_STATION")]
        FUEL_STATION,
    }
}
