// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using SpaceTraders.Client.My.Ships.Item.Scan.Ships;
using SpaceTraders.Client.My.Ships.Item.Scan.Systems;
using SpaceTraders.Client.My.Ships.Item.Scan.Waypoints;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace SpaceTraders.Client.My.Ships.Item.Scan {
    /// <summary>
    /// Builds and executes requests for operations under \my\ships\{shipSymbol}\scan
    /// </summary>
    public class ScanRequestBuilder : BaseRequestBuilder {
        /// <summary>The ships property</summary>
        public SpaceTraders.Client.My.Ships.Item.Scan.Ships.ShipsRequestBuilder Ships { get =>
            new SpaceTraders.Client.My.Ships.Item.Scan.Ships.ShipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The systems property</summary>
        public SystemsRequestBuilder Systems { get =>
            new SystemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The waypoints property</summary>
        public WaypointsRequestBuilder Waypoints { get =>
            new WaypointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new ScanRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScanRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my/ships/{shipSymbol}/scan", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new ScanRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScanRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my/ships/{shipSymbol}/scan", rawUrl) {
        }
    }
}
