// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using SpaceTraders.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace SpaceTraders.Client.My.Ships.Item.Chart {
    public class ChartPostResponse_data : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The chart of a system or waypoint, which makes the location visible to other agents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public SpaceTraders.Client.Models.Chart? Chart { get; set; }
#nullable restore
#else
        public SpaceTraders.Client.Models.Chart Chart { get; set; }
#endif
        /// <summary>A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public SpaceTraders.Client.Models.Waypoint? Waypoint { get; set; }
#nullable restore
#else
        public SpaceTraders.Client.Models.Waypoint Waypoint { get; set; }
#endif
        /// <summary>
        /// Instantiates a new chartPostResponse_data and sets the default values.
        /// </summary>
        public ChartPostResponse_data() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ChartPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ChartPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"chart", n => { Chart = n.GetObjectValue<SpaceTraders.Client.Models.Chart>(SpaceTraders.Client.Models.Chart.CreateFromDiscriminatorValue); } },
                {"waypoint", n => { Waypoint = n.GetObjectValue<SpaceTraders.Client.Models.Waypoint>(SpaceTraders.Client.Models.Waypoint.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<SpaceTraders.Client.Models.Chart>("chart", Chart);
            writer.WriteObjectValue<SpaceTraders.Client.Models.Waypoint>("waypoint", Waypoint);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
